[package]
name = "rust-dhcpclient"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dhcprs = {version = "0.1.3", path = "../rust-dhcprs"}
libc = "0.2.133"
eui48 = "1.1.0"
rand = "0.8.5"